MvcViewModels/Controllers/CitiesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MvcViewModels.Model;
using MvcViewModels.Model.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcViewModels.Controllers
{
    [Authorize]
    public class CitiesController : Controller
    {

        private readonly IPeopleService _peopleService;
        private readonly ICitysService _citysService;
        private readonly ICountryService _countryService;

        public CitiesController(IPeopleService peopleService, ICitysService citysService, ICountryService countryService)
        {
            _countryService = countryService;
            _peopleService = peopleService;
            _citysService = citysService;
        }



        // GET: PeopleController
        public ActionResult Index()
        {

            CityViewModel citysList = _citysService.All();
            return View(citysList.cityList);
        }

        // GET: PeopleController/Details/5
        public ActionResult Details(int id)
        {
            City city = _citysService.FindBy(id);

            if (city != null)
            {
                return View(city);
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: PeopleController/Create
        public ActionResult Create()
        {
            CreateCityViewModel createCityViewModel = new CreateCityViewModel();
            createCityViewModel.Countries = _countryService.All().countrieList;

            return View(createCityViewModel);
        }

        // POST: PeopleController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateCityViewModel createCityViewModel)
        {
            if (ModelState.IsValid)
            {
                createCityViewModel.Country = _countryService.FindBy(createCityViewModel.Country.Id);
                if (createCityViewModel.Country != null)
                {
                    _citysService.Add(createCityViewModel);
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(createCityViewModel);
        }

        // GET: PeopleController/Edit/5
        public ActionResult Edit(int id)
        {
            City city = _citysService.FindBy(id);

            if (city != null)
            {
                return View(city);
            }

            return RedirectToAction(nameof(Index));
        }

        // POST: PeopleController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(City city)
        {
            CreateCityViewModel createCity = new CreateCityViewModel();
            createCity.Name = city.Name;
            createCity.Country = city.Countries;


            City editCity = _citysService.Edit(city.Id, createCity);

            return RedirectToAction(nameof(Index));

        }

        // GET: PeopleController/Delete/5
        public ActionResult Delete(int id)
        {

            if (_citysService.Remove(id))
            {
                ViewBag.msg = "Person Was Removed.";
            }
            else
            {
                ViewBag.msg = "Unable to remove car with id: " + id;
            }

            return RedirectToAction(nameof(Index));


        }

        // POST: PeopleController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MvcViewModels/Controllers/CountriesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MvcViewModels.Model.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MvcViewModels.Model;
using Microsoft.AspNetCore.Authorization;

namespace MvcViewModels.Controllers
{
    [Authorize]
    public class CountriesController : Controller
    {

        private readonly ICountryService _countrysService;
        private readonly ICitysService _citysService;
        private readonly IPeopleService _peopleService;

        public CountriesController(ICitysService citysService, ICountryService countrysService, IPeopleService peopleService)
        {
            _countrysService = countrysService;
            _citysService = citysService;
            _peopleService = peopleService;
        }
        // GET: Countries
        public ActionResult Index()
        {
            CountryViewModel countryList = _countrysService.All();
            return View(countryList.countrieList);
        }
        // GET: Countries/Details/5
        public ActionResult Details(int id)
        {
            Country Country = _countrysService.FindBy(id);

            if (Country != null)
            {
                return View(Country);
            }
            return RedirectToAction(nameof(Index));

        }

        // GET: Countries/Create
        public ActionResult Create()
        {

            CreateCountryViewModel createCountryViewModel = new CreateCountryViewModel();
            createCountryViewModel.Cities = _citysService.All().cityList;


            return View(createCountryViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateCountryViewModel createCountryViewModel)
        {
            if (ModelState.IsValid)
            {

                _countrysService.Add(createCountryViewModel);
                return RedirectToAction(nameof(Index));

            }
            return View(createCountryViewModel);

        }

        public ActionResult Edit(int id)
        {
            Country country = _countrysService.FindBy(id);

            if (country != null)
            {
                return View(country);
            }
            return RedirectToAction(nameof(Index));
        }

        // POST: Countries/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Country country)
        {
            CreateCountryViewModel createCountrie = new CreateCountryViewModel();
            createCountrie.Name = country.Name;
            createCountrie.Cities = country.Cities;

            Country editCountrie = _countrysService.Edit(country.Id, createCountrie);

            return RedirectToAction(nameof(Index));

        }
        // GET: Countries/Delete/5
        public ActionResult Delete(int id)
        {
            if (_countrysService.Remove(id))
            {
                ViewBag.msg = "Person Was Removed.";
            }
            else
            {
                ViewBag.msg = "Unable to remove car with id: " + id;
            }

            return RedirectToAction(nameof(Index));
        }
        // POST: Countries/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MvcViewModels/Controllers/LanguagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcViewModels.Model.Data;
using MvcViewModels.Model.Database;
using MvcViewModels.Model;
using MvcViewModels.Model.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace MvcViewModels.Controllers
{
    [Authorize]
    public class LanguagesController : Controller
    {

        private readonly IPeopleService _peopleService;
        private readonly ILanguageService _languageService;
        public LanguagesController(IPeopleService peopleService, ILanguageService languageService)
        {
            _languageService = languageService;
            _peopleService = peopleService;
        }

        // GET: Languages
        public ActionResult Index()
        {
            LanguageViewModel languageList = _languageService.All();
            return View(languageList.LanguagesList);
        }

        // GET: Languages/Details/5
        public ActionResult Details(int id)
        {
            Language language = _languageService.FindBy(id);

            if (language != null)
            {
                return View(language);
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Languages/Create
        public IActionResult Create()
        {
            CreateLanguageViewModel createLanguageViewModel = new CreateLanguageViewModel();
            createLanguageViewModel.Languages = _languageService.All().LanguagesList;
            return View(createLanguageViewModel);
        }

        // POST: Languages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreateLanguageViewModel createLanguageViewModel)
        {
            if (ModelState.IsValid)
            {
                _languageService.Add(createLanguageViewModel);
                return RedirectToAction(nameof(Index));
            }
            return View(createLanguageViewModel);
        }

        // GET: Languages/Edit/5
        public ActionResult Edit(int id)
        {
            Language language = _languageService.FindBy(id);

            if (language != null)
            {
                return View(language);
            }
            return RedirectToAction(nameof(Index));

        }

        // POST: Languages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Language language)
        {
            CreateLanguageViewModel createLanguage = new CreateLanguageViewModel();
            createLanguage.Name = language.Name;
            //createLanguage.Languages = language.Languages;


            Language editLangue = _languageService.Edit(language.Id, createLanguage);

            return RedirectToAction(nameof(Index));

        }

        // GET: Languages/Delete/5
        public ActionResult Delete(int id)
        {

            if (_languageService.Remove(id))
            {
                ViewBag.msg = "Language Was Removed.";
            }
            else
            {
                ViewBag.msg = "Unable to remove language with id: " + id;
            }

            return RedirectToAction(nameof(Index));

        }

        // POST: Languages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MvcViewModels/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PeopleReg</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">


                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("SuperAdmin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Admin" asp-action="Index">Admin Zone</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Account" asp-action="Logout">Logout</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Languages" asp-action="Index">Languages</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Cities" asp-action="Index">Cities</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Countries" asp-action="Index">Countries</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Home" asp-action="People">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Account" asp-action="Logout">Logout</a>
                                </li>
                            }
                            else if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Languages" asp-action="Index">Languages</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Cities" asp-action="Index">Cities</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Countries" asp-action="Index">Countries</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Home" asp-action="People">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Account" asp-action="Logout">Logout</a>
                                </li>
                            }
                            else if (User.IsInRole("Member"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="People" asp-action="Index">People</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Account" asp-action="Logout">Logout</a>
                                </li>
                            }
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="SignUp">Sign Up</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PeopleReg
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

MvcViewModels/Views/Shared/_PersonCreateAjaxPartialView.cshtml
@model CreatePersonViewModel

<div id="AddId@(Model.Name)">
    <h1>Add Person</h1>

    <form asp-controller="Home" asp-action="AjaxCreateForm" onsubmit="PostCreatePersonForm(event, this)">

        <label asp-for="@Model.Name"></label>
        <input asp-for="@Model.Name" />
        <span class="text-danger" asp-validation-for="Name"></span>
        <br />
        <label asp-for="@Model.PhoneNumber"></label>
        <input asp-for="@Model.PhoneNumber" />
        <span class="text-danger" asp-validation-for="PhoneNumber"></span>
        <br />
        <label asp-for="@Model.City"></label>
        <input asp-for="@Model.City" />
        <span class="text-danger" asp-validation-for="City"></span>
        <br />
        <input type="submit" value="Create" />
    </form>
</div>

MvcViewModels/Views/Shared/_PersonDeletePartialView.cshtml
@model Person


<h1>Delete Person</h1>

<form asp-controller="Home" asp-action="Delete" onsubmit="PostDeletePersonForm(event, this)">



</form>

MvcViewModels/Views/Shared/_PersonEditPartialView.cshtml
@model Person

<div id="EditId@(Model.Id)" >


    <h1>Edit Person</h1>

    <form asp-controller="Home" asp-action="Edit" onsubmit="PostEditPersonForm(event, this)">


        
        <input type ="hidden" asp-for="@Model.Id" />
        <span class="text-danger" asp-validation-for="Id"></span>
        <label asp-for="@Model.Name"></label>
        <input asp-for="@Model.Name" />
        <span class="text-danger" asp-validation-for="Name"></span>
        <br />
        <label asp-for="@Model.PhoneNumber"></label>
        <input asp-for="@Model.PhoneNumber" />
        <span class="text-danger" asp-validation-for="PhoneNumber"></span>
        <br />
        <label asp-for="@Model.City"></label>
        <input asp-for="@Model.City" />
        <span class="text-danger" asp-validation-for="City"></span>
        <br />
        <input type="submit" value="Update" />
    </form>
</div>

MvcViewModels/Views/Shared/_PersonPartialView.cshtml
@model Person
<div id="PersonDeleteListDiv2--Home-Delete-@Model.Id">
    <div class="row">
        <div class="col">
            <p>@Model.Name</p>
        </div>
        <div class="col">
            <p>@Model.City</p>
        </div>
        <div class="col">
            <p>@Model.PhoneNumber</p>
        </div>
        <div class="col">
            <p>@Model.Id</p>
        </div>
        <div class="col">
            <a class="btn btn-danger" onclick="GetDeletePersonForm('@Url.Action("Delete")/@Model.Id')">Delete★</a>

            <a class="btn btn-secondary" onclick="GetEditPersonForm('@Url.Action("CreateEditForm")/@Model.Id')">Edit★</a>
        </div>
    </div>
</div>